spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    initialization-mode: ALWAYS
    initialize: true
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
####mail properties####
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 3b2f0977d7d477
    password: 3ebf1fbcfcf4d5
    protocol: smtp
